# ----------------------------
# Makefile Options
# ----------------------------

NAME = WIFI
DESCRIPTION = "ESP32-C3 Wi-Fi bridge"
COMPRESSED = NO

CFLAGS = -Wall -Wextra -Oz
CXXFLAGS = -Wall -Wextra -Oz

# ----------------------------

include $(shell cedev-config --makefile)
